### ISSUE TITLE
Required version of Node not specified

### ISSUE THREAD

**Issue by mccataldo** [c-h-/node-run-cmd#1]
I had issue executing likely due to the spread operator on line 109 of index.js which might not be supported in the version of Node I had installed at the time (4.3.0) because when I upgraded to the latest stable version (6.2.1), I no longer got `Unexpected token ...` . What is the oldest version of Node required?

**Comment by c-h-** [comment]
@mccataldo Sorry about that! I developed this on Node 5.4.0. I'll add it to the docs
